.TH DRC-CLI "1" "June 2016" "drc-cli 0.12"
.SH NAME
drc-cli \- a remote procedure call client for DRC Core. 
.SH SYNOPSIS
drc-cli [options] <command> [params] \- Send command to DRC Core. 
.TP
drc-cli [options] help \- Asks DRC Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the drc-cli program. drc-cli is an RPC client used to send commands to DRC Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBdrcd\fP, \fBdrc.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
